### ISSUE TITLE
qcoder doesn't create a rds file in Linux

### ISSUE THREAD

**Issue by siames3** [ropenscilabs/qcoder#182]
I am getting the following error when I try to add a new document:

```
Zip file created: /home/user/Documents/qcoder/QCoderProject-qcode_project-2019-09-25.zip
Warning in gzfile(file, "rb") :
  cannot open compressed file '/home/user/Documents/qcoder/qcode_project/data_frames/qcoder_documents_qcode_project.rds', probable reason 'No such file or directory'
Warning: Error in gzfile: cannot open the connection
  76: gzfile
  75: readRDS
  74: qcoder::add_new_documents
  73: observeEventHandler [/home/user/R/x86_64-pc-linux-gnu-library/3.6/qcoder/shiny/qcoder/app.R#425]
   2: shiny::runApp
   1: qcode
```

I checked the data_frames directory and it seems to be empty.

_Originally posted by @siames3 in https://github.com/ropenscilabs/qcoder/issues/66#issuecomment-535003105_

**Comment by siames3** [comment]
Same happens to the qcoder_units df: 

`Warning in gzfile(file, "rb") :
  cannot open compressed file '/home/user/Documents/qcoder/qcode_project/data_frames/qcoder_units_qcode_projectqcode_project.rds', probable reason 'No such file or directory'
Warning: Error in gzfile: cannot open the connection
  100: gzfile
   99: readRDS
   97: renderUI [/home/user/R/x86_64-pc-linux-gnu-library/3.6/qcoder/shiny/qcoder/app.R#431]
   96: func
   83: origRenderFunc
   82: output$checkbox_links
    2: shiny::runApp
    1: qcode
`

**Comment by elinw** [comment]
I will take a look but it sounds like another path issue.

**Comment by elinw** [comment]
Did you add the empty csv files the way it says in the readme?  We really need to make those automatically if not present, but right now it does expect that you will have those file.

**Comment by elinw** [comment]
Okay, yes I reproduced your message when the project had no created the data frames.  I did this by not importing data with import_project_data("project_name").

**Comment by elinw** [comment]
Also I merged in some changes so if you would update that might fix some things.  Let me know what happens.

**Comment by elinw** [comment]
Sorry also can you check the permissions on your folders?

**Comment by elinw** [comment]
@siames3  can you please check the current build and report back? I can't do anything without more information.

**Comment by siames3** [comment]
Hi, sorry for the late reply. I tried to install the current build and it seems to work. Thanks a lot for the support, I'll let you know if I run into problems!

**Comment by siames3** [comment]
Hi,

So I think some functionalities are working but I am still unable to load documents. I created 3 csv files in the new project directory:
codes/codes.csv,
units/units.csv
units/unit_document_map.csv

However, I get the same error when importing a document:
```

Warning in gzfile(file, "rb") :
  cannot open compressed file '/home/user/Documents/qcoder/qcode_project/data_frames/qcoder_documents_qcode_project.rds', probable reason 'No such file or directory'
Warning: Error in gzfile: cannot open the connection
  76: gzfile
  75: readRDS
  74: qcoder::add_new_documents
  73: observeEventHandler [/home/user/R/x86_64-pc-linux-gnu-library/3.6/qcoder/shiny/qcoder/app.R#432]
   2: shiny::runApp
   1: qcode
```

So apparently it's trying to read, not write, a DF. The directory permissions are the following;

```
drwxr-xr-x  2 user user 4096 Oct 14 11:35 codes
drwxr-xr-x  2 user user 4096 Oct 14 11:31 data_frames
drwxr-xr-x  3 user user 4096 Oct 14 11:32 documents
drwxr-xr-x  2 user user 4096 Oct 14 11:31 images
drwxr-xr-x  2 user user 4096 Oct 14 11:31 media
drwxr-xr-x  2 user user 4096 Oct 14 11:31 memos
drwxr-xr-x  2 user user 4096 Oct 14 11:31 misc
drwxr-xr-x  2 user user 4096 Oct 14 11:39 units
```

Thanks again!

**Comment by elinw** [comment]
To import a new document it needs to read the existing document file (which your message says doesn't exist), read the new file, and add a row to the existing file containing the data from your new document.  Can you please check to see if the /home/user/Documents/qcoder/qcode_project/data_frames/qcoder_documents_qcode_project.rds
file exists?   Are you doing this in the shiny tab for adding new data?

**Comment by siames3** [comment]
Hi,

Yes the files do not exist - the main problem is that qcoder doesn't create these files. I did it from the add data tab, yes.

**Comment by elinw** [comment]
So ... this is a bug or at least a usability problem, but try starting the whole process with the files already in the documents folder when you import the project.  It could be that there needs to be at lease one file there, but I'll work on updating so you can start with 0 files and import them all.

**Comment by elinw** [comment]
Can you let me know if my suggestion worked?

**Comment by siames3** [comment]
Hi,

When I use sample data, I can add documents and codes, yes.

**Comment by elinw** [comment]
I think the issue here is really usability, making sure that people understand the steps they have to take before starting up the shiny app.  That or add those steps (somehow) to the app itself, though I worry about it getting too  heavy.
